name = "sc-database"
compatibility_date = "2026-07-20"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "/"

[[kv_namespaces]]
binding = "SUGGESTIONS"
id = "299aebf31fad42ba8c0e454110db4980"
